### ISSUE TITLE
Upgrade to newer version of debian

### ISSUE THREAD

**Issue by enyo** [dart-lang/dart_docker#36]
[Wheezy and Jessie were recently removed from the mirror network](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository) so [running `apt-get update` in the dart Docker fails](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository).

It would be great if the dart Docker image could be based on Debian 9.

**Comment by jonasfj** [comment]
See #35 :)

**Comment by jonasfj** [comment]
note. as I read the announcemnt jessie for amd64 is not being removed, but it does appear that the updates channel did go away, which break `apt-get update` in this image.

**Comment by jonasfj** [comment]
So finding a way to release this is not trivial. Since we've been releasing with tags that follow dart-sdk version numbers.

We could do:

A) Update tags `2.2.0`, `2.2` and `2` to point to a new image based on Debian 9.
B) We could create a tag `2.2.0+1` with Debian 9 and point  `2.2` and `2` at it.
C) We could remove the broken apt-get source on the jessie image and release as `2.2.0+1` same as (B).

It feels sketchy to change the Debian version in a build-version bump (B), or just plain change the Debian version without bumping any version number. But at this point we haven't really made any promises about what these images are based on, and anyone depending on these images being jessie likely also depends on `apt-get update/install` working which they don't.
It's also worth noting that anyone who really wanted to pin these images could have used the image hash (I know I've done that when I wanted to pin docker image versions).

@kevmoo, Do you have any thoughts on this?

-------
Note. going forward we should probably refactor our tags to encode dart-sdk version and base-image, similar to how golang uses `<golangVersion>-<baseImage>` as their tags (they still have tags like `<golangVersion>` number, but at-least anyone depending on a given base image had lots of opportunity to set that constraint).

**Comment by domesticmouse** [comment]
We should actually re-release all of the older versions of Dart docker images as they are all also now broken by the Debian change. Anyone who has built their docker images pinned to a version of the Dart docker image will not be able to rebuild.

**Comment by enyo** [comment]
@domesticmouse exactly. Do you have a timeframe for this?

**Comment by jonasfj** [comment]
Okay, I talk this over with @mit-mit, @mkustermann, @athomas, and reached the conclusion that we don't support old Dart versions, we always require users to upgrade to latest Dart version. Thus, we shouldn't update old docker images either.

Instead we'll publish a new docker image as `2.2.0+1` and have tags `2`, `2.2` point to that. Leaving all the other tags alone.

**Comment by enyo** [comment]
Sounds good as well :)

**Comment by enyo** [comment]
I would be very thankful about an update when it's done.

**Comment by jonasfj** [comment]
Tags `2`, `2.2` and `2.2.0-1` have been bumped to stretch, users fo earlier images versions should upgrade.

**Comment by jonasfj** [comment]
@enyo, ^

**Comment by computmaxer** [comment]
> and reached the conclusion that we don't support old Dart versions, we always require users to upgrade to latest Dart version.

@jonasfj I'm confused why the `2.2.0` tag wasn't re-tagged with this fix like the `2.2` and `2` tags were. My understanding is that `2.2.0` is still the latest stable version of Dart.

With the current state of things, anyone using the `2.2.0` tag (which semantically means "I want the 2.2.0 version of dart") as their base image, it will fail. They will have to update their dockerfile to `2.2.0-1` (which _isn't_ a version of Dart).

In our organization we have at least 50 Dockerfiles in various repositories using the `2.2.0` tag. Would you consider re-tagging `2.2.0` as you have done for `2.2`? Thanks!

**Comment by jonasfj** [comment]
I wish I had a good answer here...

> anyone using the 2.2.0 tag (which semantically means "I want the 2.2.0 version of dart") as their base image, it will fail.

I think the problem here is that maybe we never really fully established what `2.2.0` means. Retagging `2.2.0` feels like an attempt to modify something that was released, this could lead to surprises for anyone who assumes we're not modifying our releases (which seems like a reasonable assumption). Publishing `2.2.0-1` is publishing a new repackaged version of `2.2.0`.

I don't see any good options. IMO we should clarify what the tags means going forward.

**Comment by computmaxer** [comment]
>  this could lead to surprises for anyone who assumes we're not modifying our releases

In this case, there would be no surprise other than maybe "oh, it works again!" since right now it doesn't work at all.

I agree we should clarify the tagging strategy going forward. Perhaps adding another "level" of tags would help.

Tags that allow choosing a version of Dart with varying specificity:
- `2`
- `2.2`
- `2.2.0`
Tag that allows a specifying a particular build/image:
- `2.2.0-0`

In this case when upgrading the underlying base image, the first three tags would be re-tagged at the latest, `2.2.0-0` would remain untouched, and a new `2.2.0-1` would be tagged.

**Comment by athomas** [comment]
@computmaxer We've published a repackaged version under 2.2.0 as well now.

**Comment by computmaxer** [comment]
Fantastic, thank you!

**Comment by jonasfj** [comment]
For the record, I think the point about tagging as `2.2.0-0` is solid :)
