### ISSUE TITLE
armv7 support

### ISSUE THREAD

**Issue by Derrick56007** [dart-lang/dart_docker#64]
Is there any way we can get images built for armv7?

**Comment by cpswan** [comment]
Hi @Derrick56007 it looks like the Dart team are starting over with their Docker images. Take a look at https://github.com/dart-lang/dart-docker/issues/11 for a thread on Arm support.

I've been trying some stuff myself on this in the past few days, and I've got things working when building on a Raspberry Pi, but various aspects of cross platform builds with QEMU/Docker buildx seem to be broken for armv7 (because as a friend said to me earlier today "armv7 is a mess").

**Comment by athomas** [comment]
Correct, we've considered refactoring this repo but a clean slate makes it easier for us to follow best practices and still publish the "classic" images for a while to give people a chance to migrate. We will not be adding arm support here, but we plan to do it in the new repo.
